### ISSUE TITLE
Lisk Service failing to reconnect to Lisk Core (intermittent)

### ISSUE THREAD

**Issue by Nazgolze** [LiskHQ/lisk-service#1000]
### Actual behavior
Lisk Service will lose its connection to Lisk Core and then sometimes fail to reconnect
The RequestTimeoutError below will repeat until it's manually restarted
```
2022-03-11T12:13:54.322 WARN [BROKER] Service 'core.network.status' is not available.
2022-03-11T12:13:55.940 WARN [BROKER] Service 'core.network.status' is not available.
2022-03-11T12:13:55.961 WARN [BROKER] Service 'core.network.status' is not available.
2022-03-11T12:13:56.240 WARN [BROKER] Service 'core.network.status' is not available.
2022-03-11T12:13:56.360 WARN [BROKER] Service 'core.network.status' is not available.
2022-03-11T12:13:56.991 INFO [REGISTRY] Node 'core.my_host-1' reconnected.
2022-03-11T12:14:07.963 WARN [BROKER] Request 'core.network.status' is timed out.,[object Object]
2022-03-11T12:14:07.965 ERROR [GATEWAY] <= 504 Request error: RequestTimeoutError: Request is timed out whe
n call 'core.network.status' action on 'core.my_host-1' node.
RequestTimeoutError: Request is timed out when call 'core.network.status' action on 'core.my_host-1' node.
    at /home/lisk/lisk-service/gateway/node_modules/moleculer/src/middlewares/timeout.js:42:14
    at async getStatus (/home/lisk/lisk-service/gateway/shared/status.js:36:24)
    at async Service.callAction (/home/lisk/lisk-service/gateway/shared/moleculer-web/methods.js:100:16)
    at async /home/lisk/lisk-service/gateway/node_modules/moleculer-web/src/index.js:443:22
Data:
Request params: {}
Request body: {}
2022-03-11T12:14:07.983 WARN [BROKER] Request 'core.network.status' is timed out.,[object Object]
2022-03-11T12:14:07.984 ERROR [GATEWAY] <= 504 Request error: RequestTimeoutError: Request is timed out whe
n call 'core.network.status' action on 'core.my_host-1' node.
RequestTimeoutError: Request is timed out when call 'core.network.status' action on 'core.my_host-1' node.
    at /home/lisk/lisk-service/gateway/node_modules/moleculer/src/middlewares/timeout.js:42:14
    at async getStatus (/home/lisk/lisk-service/gateway/shared/status.js:36:24)
    at async Service.callAction (/home/lisk/lisk-service/gateway/shared/moleculer-web/methods.js:100:16)
    at async /home/lisk/lisk-service/gateway/node_modules/moleculer-web/src/index.js:443:22
Data:
Request params: {}
Request body: {}
2022-03-11T12:14:08.273 WARN [BROKER] Request 'core.network.status' is timed out.,[object Object]
```
### Expected behavior
It should eventually succeed in reconnecting
### Steps to reproduce
It's intermittent 
### Which version(s) does this affect? (Environment, OS, etc...)
3.0.3, Linux, Docker

**Comment by Nazgolze** [comment]
I may have misinterpreted the problem. Will try to get more logs the next time it happens

**Comment by Nazgolze** [comment]
These logs are from the core service, same as what's seen above:
```
2022-03-12T20:35:41.866 WARN [BROKER] Request 'core.network.status' is timed out.,[object Object]
2022-03-12T20:35:42.206 WARN [BROKER] Request 'core.network.status' is timed out.,[object Object]
2022-03-12T20:35:42.838 WARN [BROKER] Request 'core.network.status' is timed out.,[object Object]
2022-03-12T20:35:42.931 WARN [BROKER] Request 'core.network.status' is timed out.,[object Object]
```

Restarting only that one container resolves it. I think I was right the first time :sweat_smile:

**Comment by lisknonanika** [comment]
The same issue occurs from time to time.
In particular, /blocks and /transactions may time out.
But, the core api works fine, so it may be an environmental issue.
