### ISSUE TITLE
Transaction indexing failure

### ISSUE THREAD

**Issue by sameersubudhi** [LiskHQ/lisk-service#1448]
### Actual behavior
Post the Lisk SDK alpha.11 update, Lisk Service is unable to index transactions and fails with the following error.

```
2023-01-17T21:48:21.687 WARN [blockchainIndex] Error: Event unavailable to determine execution status for transaction: 284e0faacfdfe1a6a22d4fdf42cbc0fc6eeac6f947f6a4b0ac4809f56023471e.
    at getTransactionExecutionStatus (/Users/sameer/Documents/Lisk/github/lisk-service/services/blockchain-indexer/shared/indexer/blockchainIndex.js:107:32)
    at BluebirdPromise.map.concurrency (/Users/sameer/Documents/Lisk/github/lisk-service/services/blockchain-indexer/shared/indexer/blockchainIndex.js:158:27)
    at tryCatcher (/Users/sameer/Documents/Lisk/github/lisk-service/services/blockchain-indexer/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/Users/sameer/Documents/Lisk/github/lisk-service/services/blockchain-indexer/node_modules/bluebird/js/release/map.js:68:38)
    at MappingPromiseArray.PromiseArray._iterate (/Users/sameer/Documents/Lisk/github/lisk-service/services/blockchain-indexer/node_modules/bluebird/js/release/promise_array.js:115:31)
    at MappingPromiseArray.init (/Users/sameer/Documents/Lisk/github/lisk-service/services/blockchain-indexer/node_modules/bluebird/js/release/promise_array.js:79:10)
    at MappingPromiseArray._asyncInit (/Users/sameer/Documents/Lisk/github/lisk-service/services/blockchain-indexer/node_modules/bluebird/js/release/map.js:37:10)
    at _drainQueueStep (/Users/sameer/Documents/Lisk/github/lisk-service/services/blockchain-indexer/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/Users/sameer/Documents/Lisk/github/lisk-service/services/blockchain-indexer/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/sameer/Documents/Lisk/github/lisk-service/services/blockchain-indexer/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues (/Users/sameer/Documents/Lisk/github/lisk-service/services/blockchain-indexer/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:466:21)
    at process.callbackTrampoline (node:internal/async_hooks:130:17)
```

### Expected behavior
Lisk Service should be able to index transactions without errors.

### Steps to reproduce
- Run Lisk Service against Lisk Core and post any transaction. (Both need to be on the aforementioned SDK versions)
- Watch the logs

### Which version(s) does this affect? (Environment, OS, etc...)
Lisk Service (on Lisk SDK v6.0.0-alpha.11)

**Comment by ManuGowda** [comment]
This issue is no longer reproducible after Lisk SDK alpha.13 release
