### ISSUE TITLE
Fix dynamic fees errors

### ISSUE THREAD

**Issue by sameersubudhi** [LiskHQ/lisk-service#211]
### Actual behavior
Seeing the below errors originating from/in `dynamicFees.js`:
```
(node:6688) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'height' of undefined
    at /Users/sameer/Documents/Lisk/github/lisk-service/services/core/shared/core/blocks.js:99:51
    at Array.map (<anonymous>)
    at getBlocksFromCache (/Users/sameer/Documents/Lisk/github/lisk-service/services/core/shared/core/blocks.js:97:27)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getBlocks (/Users/sameer/Documents/Lisk/github/lisk-service/services/core/shared/core/blocks.js:141:17)
    at async blockBatch.data.BluebirdPromise.map.concurrency (/Users/sameer/Documents/Lisk/github/lisk-service/services/core/shared/core/dynamicFees.js:236:16)
```

```
(node:15249) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'id' of undefined
    at blockBatch.data.BluebirdPromise.map.concurrency (/Users/sameer/Documents/Lisk/github/lisk-service/services/core/shared/core/dynamicFees.js:243:79)
    at tryCatcher (/Users/sameer/Documents/Lisk/github/lisk-service/services/core/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/Users/sameer/Documents/Lisk/github/lisk-service/services/core/node_modules/bluebird/js/release/map.js:68:38)
    at MappingPromiseArray.PromiseArray._iterate (/Users/sameer/Documents/Lisk/github/lisk-service/services/core/node_modules/bluebird/js/release/promise_array.js:115:31)
    at MappingPromiseArray.init (/Users/sameer/Documents/Lisk/github/lisk-service/services/core/node_modules/bluebird/js/release/promise_array.js:79:10)
    at MappingPromiseArray._asyncInit (/Users/sameer/Documents/Lisk/github/lisk-service/services/core/node_modules/bluebird/js/release/map.js:37:10)
    at _drainQueueStep (/Users/sameer/Documents/Lisk/github/lisk-service/services/core/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/Users/sameer/Documents/Lisk/github/lisk-service/services/core/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/sameer/Documents/Lisk/github/lisk-service/services/core/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues (/Users/sameer/Documents/Lisk/github/lisk-service/services/core/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
    at process.callbackTrampoline (internal/async_hooks.js:120:14)
(node:15249) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 83)
```
### Expected behavior
Lisk Service - Core service logs should be clean and not reporting the above errors.

### Steps to reproduce
Start the Lisk Service - Core service against `https://betanet.lisk.io` and watch the logs for Lisk Service - Core service.

### Which version(s) does this affect? (Environment, OS, etc...)
NA

**Comment by MichalTuleja** [comment]
Reopened due to the recurring problems.
