### ISSUE TITLE
Binance import error

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisk-service#793]
### Actual behavior

During refreshing the data source from Binance the following error occurs:

```
 2021-09-24T09:23:05.118 ERROR [binance] TypeError: Cannot read property 'data' of undefined
     at fetchAllMarketTickers (/home/lisk/lisk-service/market/shared/market/sources/binance.js:52:19)
     at async reload (/home/lisk/lisk-service/market/shared/market/sources/binance.js:100:19)
     at async Task.controller [as execution] (/home/lisk/lisk-service/market/jobs/binance.js:30:4)
 TypeError: tickers.filter is not a function
     at filterTickers (/home/lisk/lisk-service/market/shared/market/sources/binance.js:62:34)
     at reload (/home/lisk/lisk-service/market/shared/market/sources/binance.js:101:27)
     at async Task.controller [as execution] (/home/lisk/lisk-service/market/jobs/binance.js:30:4)
```

### Expected behavior

Make sure the data from Binance is retrieved without problems.

### Steps to reproduce

Start the process and observe logs.

### Which version(s) does this affect? (Environment, OS, etc...)

`0.5.0-alpha.0`

**Comment by MichalTuleja** [comment]
Possible duplicate of #806.
