### ISSUE TITLE
Improve error handling in market microservice

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisk-service#806]
### Description

Usually the following errors are visible when the service is run for a while.

```
market_1                  | TypeError: tickers.filter is not a function
market_1                  |     at filterTickers (/home/lisk/lisk-service/market/shared/market/sources/bittrex.js:51:34)
market_1                  |     at reload (/home/lisk/lisk-service/market/shared/market/sources/bittrex.js:90:27)
market_1                  |     at async Task.controller [as execution] (/home/lisk/lisk-service/market/jobs/bittrex.js:30:4)
market_1                  | 2021-10-11T13:59:05.110 ERROR [bittrex] Cannot read property 'data' of undefined
market_1                  | 2021-10-11T13:59:05.110 ERROR [bittrex] TypeError: Cannot read property 'data' of undefined
market_1                  |     at fetchAllMarketTickers (/home/lisk/lisk-service/market/shared/market/sources/bittrex.js:41:19)
market_1                  |     at async reload (/home/lisk/lisk-service/market/shared/market/sources/bittrex.js:89:19)
market_1                  |     at async Task.controller [as execution] (/home/lisk/lisk-service/market/jobs/bittrex.js:30:4)
```

Improve data validation and prevent from throwing the call stack in on data retrieval errors.

### Acceptance Criteria

- The console logs keep the warning message with an explanation, such as validation error or data retrieval error.

**Comment by sameersubudhi** [comment]
This issue has already been addressed in PR https://github.com/LiskHQ/lisk-service/pull/959.
