### ISSUE TITLE
Mitigate MySQL layer deadlock issue

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisk-service#820]
### Actual behavior

During the initial import, the database reports deadlocks. That issue is present since the transactional approach was implemented.

```
core_1                    | 2021-10-14T21:07:30.608 INFO [blockchainIndex] currentChainHeight: 16728078, lastIndexedBlock: 16728078
core_1                    | 2021-10-14T21:07:30.609 INFO [blockchainIndex] Block index status: 129773/457786 blocks indexed (28.34%)
core_1                    | 2021-10-14T21:07:32.721 WARN [queue] indexAccountsQueue Job failed,insert into `votes_aggregate` (`amount`, `id`, `receivedAddress`, `sentAddress`, `timestamp`) values ('751000000000', 'lsk2nu5dcjfxqu66bxfemu4wzqhykxpyyvhhavc2slskmwzf5unkxtjwbvosy3kcj44t49u4zrmdeok944', 'lsk2nu5dcjfxqu66bxfemu4wzqhykxpyyvhhavc2s', 'lskmwzf5unkxtjwbvosy3kcj44t49u4zrmdeok944', 1632943660) on duplicate key update `amount` = values(`amount`), `id` = values(`id`), `receivedAddress` = values(`receivedAddress`), `sentAddress` = values(`sentAddress`), `timestamp` = values(`timestamp`) - ER_LOCK_DEADLOCK: Deadlock found when trying to get lock; try restarting transaction
core_1                    | 2021-10-14T21:07:32.721 WARN [queue] indexAccountsQueue Job failed,Error: ER_LOCK_DEADLOCK: Deadlock found when trying to get lock; try restarting transaction
core_1                    |     at Query.Sequence._packetToError (/home/lisk/lisk-service/core/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
core_1                    |     at Query.ErrorPacket (/home/lisk/lisk-service/core/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
core_1                    |     at Protocol._parsePacket (/home/lisk/lisk-service/core/node_modules/mysql/lib/protocol/Protocol.js:291:23)
core_1                    |     at Parser._parsePacket (/home/lisk/lisk-service/core/node_modules/mysql/lib/protocol/Parser.js:433:10)
```

### Expected behavior

The deadlock issues are not present anymore.

### Steps to reproduce

Run the process on a clear database against testnet or mainnet.

For a better chance to reproduce that issue, increase the simultaneous block queue processing to >50.

### Which version(s) does this affect? (Environment, OS, etc...)

0.5.0-beta.0

**Comment by MichalTuleja** [comment]
The deadlock issue is not causing discrepancies between the blockchain and the index. There were several solutions discussed:

- Whitelisting the log warning `ER_LOCK_DEADLOCK`
- Reducing queue concurrency to `1`
- Maintaining a new table with incremental values
- Using a sequence (Supported by MariaDB, but not MySQL)
